version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-microservice
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mysql-database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: